title: Chinonye Aniagolu
#logo: /assests/img/headshot_circle.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
# files:
#   - /index.html
#   - /styles.css
#   - /scripts.js
#   - /assets/images/
#   - /assets/resume.pdf
